version: "3.8"

services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - vault-data:/vault/data
    restart: always
    healthcheck:
      test: ["CMD", "/bin/vault", "status"]
      interval: 30s
      timeout: 5s
      retries: 3

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "myroot"
    volumes:
      - .:/app  # OK if you're developing locally
    depends_on:
      vault:
        condition: service_healthy

  

volumes:
  vault-data:
